/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FlightAdministration;
import java.awt.event.KeyEvent;
import java.awt.*;
import java.sql.*;
import java.io.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author kitaa
 */

public class flight extends javax.swing.JFrame {
static Connection conn;
static Statement stmt;
static ResultSet rs;
    /**
     * Creates new form 
     */
    public flight() {
        koneksi();
        initComponents();
        setLocationRelativeTo(this);
        loadAllFlights();
    }
    
    public void koneksi() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/TubesPBO?useSSL=false&serverTimezone=UTC","root","");
            stmt = conn.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi database gagal: " + e.getMessage());
        }
    }
    
    public void loadAllFlights() {
        Object[] Baris = {"idFlight", "Nomor Penerbangan", "Maskapai", "Bandara_Asal", "Bandara_Tujuan", "Tanggal", "Keberangkatan", "Tiba", "Status"};
        DefaultTableModel tabmode = new DefaultTableModel(null, Baris);
        jTable1.setModel(tabmode);
        try {
            rs = stmt.executeQuery("SELECT * FROM flight");
            while (rs.next()) {
                String a = rs.getString("idFlight");
                String b = rs.getString("Nomor_Penerbangan");
                String c = rs.getString("Maskapai");
                String d = rs.getString("Bandara_Asal");
                String e = rs.getString("Bandara_Tujuan");
                String f = rs.getString("Tanggal");
                String g = rs.getString("Keberangkatan");
                String h = rs.getString("Tiba");
                String i = rs.getString("Status");
                String[] data = {a, b, c, d, e, f, g, h, i};
                tabmode.addRow(data);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data penerbangan: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelTicket = new javax.swing.JLabel();
        jLabelAirport = new javax.swing.JLabel();
        jLabelFlight = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonHapusFlight = new javax.swing.JButton();
        jButtonFlightBaru = new javax.swing.JButton();
        jButtonLihatSemua = new javax.swing.JButton();
        jButtonEditStatus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButtonCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, -1));

        jPanel2.setBackground(new java.awt.Color(52, 54, 53));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightAdministration/images/user.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, -1, -1));

        jLabelTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightAdministration/images/TiketSmall.png"))); // NOI18N
        jLabelTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTicketMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabelAirport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightAdministration/images/airports.png"))); // NOI18N
        jLabelAirport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAirportMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabelFlight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightAdministration/images/timetable.png"))); // NOI18N
        jLabelFlight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFlightMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelFlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightAdministration/images/PlaneSmall.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 232, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 60, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightAdministration/images/menu hamburger.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 60, 700));

        jPanel5.setBackground(new java.awt.Color(229, 229, 229));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setText("ID_Flight");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 300, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightAdministration/images/magnifier.png"))); // NOI18N
        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, -1, 30));

        jPanel3.setBackground(new java.awt.Color(229, 229, 229));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tools", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Sitka Heading", 1, 24))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jButtonHapusFlight.setText("Hapus Flight");
        jButtonHapusFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusFlightActionPerformed(evt);
            }
        });

        jButtonFlightBaru.setText("Flight Baru");
        jButtonFlightBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFlightBaruActionPerformed(evt);
            }
        });

        jButtonLihatSemua.setText("Lihat semua");
        jButtonLihatSemua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLihatSemuaActionPerformed(evt);
            }
        });

        jButtonEditStatus.setText("Edit Status");
        jButtonEditStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditStatusActionPerformed(evt);
            }
        });

        jLabel2.setText("Tanggal:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Asal:");

        jLabel11.setText("Tujuan:");

        jButtonCari.setText("Cari");
        jButtonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEditStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLihatSemua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonHapusFlight, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(jButtonFlightBaru, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCari, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCari)
                .addGap(47, 47, 47)
                .addComponent(jButtonFlightBaru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonHapusFlight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEditStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButtonLihatSemua)
                .addGap(24, 24, 24))
        );

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 70, 150, 440));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "idFlight", "Nomor Penerbangan", "Maskapai", "Bandara Asal", "Bandara Tujuan", "Tanggal", "Keberangkatan", "Tiba", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 71, 940, 460));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 1150, 560));

        jPanel6.setBackground(new java.awt.Color(255, 232, 40));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(229, 229, 229));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel1.setText("Flight");
        jPanel13.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 200, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightAdministration/images/timetable (1).png"))); // NOI18N
        jPanel13.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightAdministration/images/penumpang.jpg.png"))); // NOI18N
        jPanel13.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -300, -1, -1));

        jPanel6.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1150, 90));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 1150, 110));

        jPanel14.setBackground(new java.awt.Color(9, 132, 202));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 1150, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTicketMouseClicked
        // TODO add your handling code here:
          new ticketUI().setVisible(true);
          dispose();
    }//GEN-LAST:event_jLabelTicketMouseClicked

    private void jLabelAirportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAirportMouseClicked
        // TODO add your handling code here:
          new airport().setVisible(true);
          dispose();
    }//GEN-LAST:event_jLabelAirportMouseClicked

    private void jLabelFlightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFlightMouseClicked
        // TODO add your handling code here:
        new flight().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelFlightMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
         new Pesawat().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
         new mainmenu().setVisible(true);
          dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonHapusFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusFlightActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih flight yang akan dihapus.");
            return;
        }

        String idFlight = jTable1.getValueAt(selectedRow, 0).toString();
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus flight dengan ID " + idFlight + "?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                String query = "DELETE FROM flight WHERE idFlight = ?";
                PreparedStatement pstmt = conn.prepareStatement(query);
                pstmt.setString(1, idFlight);
                int rowsAffected = pstmt.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Flight berhasil dihapus!");
                    loadAllFlights();
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus flight.");
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal menghapus flight: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonHapusFlightActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCariActionPerformed
        // TODO add your handling code here:
        String tanggal = jTextField2.getText().trim();
        String asal = jTextField3.getText().trim();
        String tujuan = jTextField4.getText().trim();

        if (tanggal.isEmpty() && asal.isEmpty() && tujuan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan setidaknya satu kriteria pencarian (Tanggal, Asal, atau Tujuan).");
            return;
        }

        StringBuilder query = new StringBuilder("SELECT * FROM flight WHERE 1=1");
        if (!tanggal.isEmpty()) {
            query.append(" AND Tanggal = '").append(tanggal).append("'");
        }
        if (!asal.isEmpty()) {
            query.append(" AND `Bandara Asal` LIKE '%").append(asal).append("%'");
        }
        if (!tujuan.isEmpty()) {
            query.append(" AND `Bandara Tujuan` LIKE '%").append(tujuan).append("%'");
        }

        Object[] Baris = {"idFlight", "Nomor Penerbangan", "Maskapai", "Bandara Asal", "Bandara Tujuan", "Tanggal", "Keberangkatan", "Tiba", "Status"};
        DefaultTableModel tabmode = new DefaultTableModel(null, Baris);
        jTable1.setModel(tabmode);

        try {
            rs = stmt.executeQuery(query.toString());
            while (rs.next()) {
                String[] data = {
                    rs.getString("idFlight"),
                    rs.getString("Nomor_Penerbangan"),
                    rs.getString("Maskapai"),
                    rs.getString("Bandara Asal"),
                    rs.getString("Bandara Tujuan"),
                    rs.getString("Tanggal"),
                    rs.getString("Keberangkatan"),
                    rs.getString("Tiba"),
                    rs.getString("Status")
                };
                tabmode.addRow(data);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal mencari data penerbangan: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonCariActionPerformed

    private void jButtonFlightBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFlightBaruActionPerformed
        // TODO add your handling code here:
        JTextField idField = new JTextField(10);
        JTextField nomorField = new JTextField(10);
        JTextField maskapaiField = new JTextField(10);
        JTextField asalField = new JTextField(10);
        JTextField tujuanField = new JTextField(10);
        JTextField tanggalField = new JTextField(10);
        JTextField keberangkatanField = new JTextField(10);
        JTextField tibaField = new JTextField(10);
        JTextField statusField = new JTextField(10);

        JPanel panel = new JPanel(new GridLayout(9, 2));
        panel.add(new JLabel("ID Flight:"));
        panel.add(idField);
        panel.add(new JLabel("Nomor Penerbangan:"));
        panel.add(nomorField);
        panel.add(new JLabel("Maskapai:"));
        panel.add(maskapaiField);
        panel.add(new JLabel("Bandara Asal:"));
        panel.add(asalField);
        panel.add(new JLabel("Bandara Tujuan:"));
        panel.add(tujuanField);
        panel.add(new JLabel("Tanggal (YYYY-MM-DD):"));
        panel.add(tanggalField);
        panel.add(new JLabel("Keberangkatan (HH:MM:SS):"));
        panel.add(keberangkatanField);
        panel.add(new JLabel("Tiba (HH:MM:SS):"));
        panel.add(tibaField);
        panel.add(new JLabel("Status:"));
        panel.add(statusField);

        int result = JOptionPane.showConfirmDialog(this, panel, "Tambah Flight Baru", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            try {
                String query = "INSERT INTO flight (idFlight, Nomor_Penerbangan, Maskapai, `Bandara Asal`, `Bandara Tujuan`, Tanggal, Keberangkatan, Tiba, Status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement pstmt = conn.prepareStatement(query);
                pstmt.setString(1, idField.getText());
                pstmt.setString(2, nomorField.getText());
                pstmt.setString(3, maskapaiField.getText());
                pstmt.setString(4, asalField.getText());
                pstmt.setString(5, tujuanField.getText());
                pstmt.setString(6, tanggalField.getText());
                pstmt.setString(7, keberangkatanField.getText());
                pstmt.setString(8, tibaField.getText());
                pstmt.setString(9, statusField.getText());

                int rowsAffected = pstmt.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Flight berhasil ditambahkan!");
                    loadAllFlights();
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menambahkan flight.");
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal menambahkan flight: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonFlightBaruActionPerformed

    private void jButtonEditStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditStatusActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih flight yang statusnya akan diedit.");
            return;
        }

        String idFlight = jTable1.getValueAt(selectedRow, 0).toString();
        String currentStatus = jTable1.getValueAt(selectedRow, 8).toString();
        String newStatus = JOptionPane.showInputDialog(this, "Masukkan status baru untuk flight " + idFlight + " (sebelumnya: " + currentStatus + "):", currentStatus);
        if (newStatus != null && !newStatus.trim().isEmpty()) {
            try {
                String query = "UPDATE flight SET Status = ? WHERE idFlight = ?";
                PreparedStatement pstmt = conn.prepareStatement(query);
                pstmt.setString(1, newStatus);
                pstmt.setString(2, idFlight);
                int rowsAffected = pstmt.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Status flight berhasil diperbarui!");
                    loadAllFlights();
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal memperbarui status flight.");
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal memperbarui status: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonEditStatusActionPerformed

    private void jButtonLihatSemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLihatSemuaActionPerformed
        // TODO add your handling code here:
        loadAllFlights();
    }//GEN-LAST:event_jButtonLihatSemuaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String idFlight = jTextField1.getText().trim();

        if (idFlight.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan ID Flight untuk mencari.");
            return;
        }

        Object[] Baris = {"idFlight", "Nomor Penerbangan", "Maskapai", "Bandara Asal", "Bandara Tujuan", "Tanggal", "Keberangkatan", "Tiba", "Status"};
        DefaultTableModel tabmode = new DefaultTableModel(null, Baris);
        jTable1.setModel(tabmode);

        try {
            String query = "SELECT * FROM flight WHERE idFlight = '" + idFlight + "'";
            rs = stmt.executeQuery(query);
            if (rs.next()) {
                String[] data = {
                    rs.getString("idFlight"),
                    rs.getString("Nomor_Penerbangan"),
                    rs.getString("Maskapai"),
                    rs.getString("Bandara Asal"),
                    rs.getString("Bandara Tujuan"),
                    rs.getString("Tanggal"),
                    rs.getString("Keberangkatan"),
                    rs.getString("Tiba"),
                    rs.getString("Status")
                };
                tabmode.addRow(data);
            } else {
                JOptionPane.showMessageDialog(this, "ID Flight tidak ditemukan.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal mencari data penerbangan: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new flight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCari;
    private javax.swing.JButton jButtonEditStatus;
    private javax.swing.JButton jButtonFlightBaru;
    private javax.swing.JButton jButtonHapusFlight;
    private javax.swing.JButton jButtonLihatSemua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelAirport;
    private javax.swing.JLabel jLabelFlight;
    private javax.swing.JLabel jLabelTicket;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
