/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FlightAdministration;
import java.awt.event.KeyEvent;
import java.awt.*;
import java.sql.*;
import java.io.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author kitaaaa
 */

public class Pesawat extends javax.swing.JFrame {
static Connection conn;
static Statement stmt;
static ResultSet rs;
    
    /**
     * Creates new form 
     */
    public Pesawat() {
        koneksi();
        initComponents();
        setLocationRelativeTo(this);
        loadAllPesawat();
    }
    public void koneksi(){
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/TubesPBO?useSSL=false&serverTimezone=UTC","root","");
        stmt = conn.createStatement();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi database gagal: " + e.getMessage());
        }
    }
    
public void loadAllPesawat(){
        Object[] Baris = {"Id_Pesawat", "Model", "Kapasitas"};
        DefaultTableModel tabmode =new DefaultTableModel(null,Baris);
        jTable1.setModel(tabmode);
        try{
            rs = stmt.executeQuery("SELECT * FROM pesawat");
            while(rs.next()){
                String a=rs.getString("Id_Pesawat");
                String b=rs.getString("Model");
                String c=rs.getString("Kapasitas");
                String[] data={a, b, c};
                tabmode.addRow(data);
            }
           
        }catch(Exception e){}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelTicket = new javax.swing.JLabel();
        jLabelAirport = new javax.swing.JLabel();
        jLabelFlight = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelPesawat = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButtonCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButtonHapusPesawat = new javax.swing.JButton();
        jButtonTambahPesawat = new javax.swing.JButton();
        jButtonLihatSemua = new javax.swing.JButton();
        jButtonEditPesawat = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, -1));

        jPanel2.setBackground(new java.awt.Color(52, 54, 53));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightAdministration/images/user.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, -1, -1));

        jLabelTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightAdministration/images/TiketSmall.png"))); // NOI18N
        jLabelTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTicketMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabelAirport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightAdministration/images/airports.png"))); // NOI18N
        jLabelAirport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAirportMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabelFlight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightAdministration/images/timetable.png"))); // NOI18N
        jLabelFlight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFlightMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelFlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 232, 40));

        jLabelPesawat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightAdministration/images/PlaneSmall.png"))); // NOI18N
        jLabelPesawat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPesawatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabelPesawat)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelPesawat)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 60, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightAdministration/images/menu hamburger.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 60, 700));

        jPanel5.setBackground(new java.awt.Color(229, 229, 229));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 300, 30));

        jButtonCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightAdministration/images/magnifier.png"))); // NOI18N
        jButtonCari.setText("Cari");
        jButtonCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCariMouseClicked(evt);
            }
        });
        jButtonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCariActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, -1, 30));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id_Pesawat", "Model", "Capacity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 71, 930, 450));

        jPanel3.setBackground(new java.awt.Color(229, 229, 229));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tools", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Sitka Heading", 1, 24))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jButtonHapusPesawat.setText("Hapus Pesawat");
        jButtonHapusPesawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusPesawatActionPerformed(evt);
            }
        });

        jButtonTambahPesawat.setText("Tambah Pesawat");
        jButtonTambahPesawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahPesawatActionPerformed(evt);
            }
        });

        jButtonLihatSemua.setText("Lihat semua");
        jButtonLihatSemua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLihatSemuaActionPerformed(evt);
            }
        });

        jButtonEditPesawat.setText("Edit Pesawat");
        jButtonEditPesawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditPesawatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEditPesawat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLihatSemua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonHapusPesawat, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(jButtonTambahPesawat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButtonTambahPesawat)
                .addGap(18, 18, 18)
                .addComponent(jButtonHapusPesawat)
                .addGap(18, 18, 18)
                .addComponent(jButtonEditPesawat)
                .addGap(18, 18, 18)
                .addComponent(jButtonLihatSemua)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 70, 150, 440));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 1150, 540));

        jPanel6.setBackground(new java.awt.Color(255, 232, 40));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(32, 47, 90));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 20, -1, -1));

        jPanel13.setBackground(new java.awt.Color(229, 229, 229));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel13.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -300, -1, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel1.setText("Pesawat");
        jPanel13.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jPanel7.setBackground(new java.awt.Color(9, 132, 202));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightAdministration/images/Plane.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel13.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel6.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1150, 110));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 1150, 130));

        jPanel14.setBackground(new java.awt.Color(9, 132, 202));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 1150, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabelTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTicketMouseClicked
        // TODO add your handling code here:
         new ticketUI().setVisible(true);
         dispose();
    }//GEN-LAST:event_jLabelTicketMouseClicked

    private void jLabelAirportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAirportMouseClicked
        // TODO add your handling code here:
          new airport().setVisible(true);
          dispose();
    }//GEN-LAST:event_jLabelAirportMouseClicked

    private void jLabelFlightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFlightMouseClicked
        // TODO add your handling code here:
        new flight().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelFlightMouseClicked

    private void jLabelPesawatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPesawatMouseClicked
        // TODO add your handling code here:
         new Pesawat().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelPesawatMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        new mainmenu().setVisible(true);
          dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButtonLihatSemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLihatSemuaActionPerformed
        // TODO add your handling code here:
        Object[] Baris = {"Id_Pesawat", "Model", "Kapasitas"};
        DefaultTableModel tabmode = new DefaultTableModel(null, Baris);
        jTable1.setModel(tabmode);

        try {
            String sql = "SELECT id_pesawat, model, kapasitas FROM pesawat";
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                String[] data = {
                    rs.getString("id_pesawat"),
                    rs.getString("model"),
                    rs.getString("kapasitas")
                };
                tabmode.addRow(data);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error memuat data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }                 
    }//GEN-LAST:event_jButtonLihatSemuaActionPerformed

    private void jButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCariActionPerformed
        // TODO add your handling code here:
        String search = jTextField1.getText().trim();
        Object[] Baris = {"Id_Pesawat", "Model", "Kapasitas"};
        DefaultTableModel tabmode = new DefaultTableModel(null, Baris);
        jTable1.setModel(tabmode);

        try {
            String sql = "SELECT id_pesawat, model, kapasitas FROM pesawat WHERE model LIKE ? OR id_pesawat LIKE ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, "%" + search + "%");
            pstmt.setString(2, "%" + search + "%");
            ResultSet rs = pstmt.executeQuery();

            while (rs.next()) {
                String[] data = {
                    rs.getString("id_pesawat"),
                    rs.getString("model"),
                    rs.getString("kapasitas")
                };
                tabmode.addRow(data);
            }
            if (tabmode.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Pesawat tidak ditemukan!", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error mencari data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCariActionPerformed

    private void jButtonTambahPesawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahPesawatActionPerformed
        // TODO add your handling code here:
        new tambahpesawat().setVisible(true);
    }//GEN-LAST:event_jButtonTambahPesawatActionPerformed

    private void jButtonEditPesawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditPesawatActionPerformed
        // TODO add your handling code here:
        new editpesawat().setVisible(true);
    }//GEN-LAST:event_jButtonEditPesawatActionPerformed

    private void jButtonHapusPesawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusPesawatActionPerformed
        // TODO add your handling code here:
        new hapuspesawat().setVisible(true);
    }//GEN-LAST:event_jButtonHapusPesawatActionPerformed

    private void jButtonCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCariMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonCariMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesawat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCari;
    private javax.swing.JButton jButtonEditPesawat;
    private javax.swing.JButton jButtonHapusPesawat;
    private javax.swing.JButton jButtonLihatSemua;
    private javax.swing.JButton jButtonTambahPesawat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAirport;
    private javax.swing.JLabel jLabelFlight;
    private javax.swing.JLabel jLabelPesawat;
    private javax.swing.JLabel jLabelTicket;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
