/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FlightAdministration;
import java.awt.event.KeyEvent;
import java.awt.*;
import java.sql.*;
import java.io.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author kitaa
 */

public class ticketUI extends javax.swing.JFrame {
private String currentFlightNumber = null;
static Connection conn;
static Statement stmt;
static ResultSet rs;
    
    /**
     * Creates new form 
     */
    public ticketUI() {
        koneksi();
        initComponents();
        setLocationRelativeTo(this);
        loadAllTickets(); // Load all tickets on startup
    }
    
    public void koneksi(){
    try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/TubesPBO?useSSL=false&serverTimezone=UTC","root","");
        stmt = conn.createStatement();
    }catch (Exception e){}; 
        
    }
    
public void loadAllTickets() {
        Object[] Baris = {"ID Tiket", "Nama Penumpang", "Penerbangan", "Kelas", "Kursi", "Food", "Suite", "Tujuan", "Waktu Berangkat"};
        DefaultTableModel tabmode = new DefaultTableModel(null, Baris);
        jTable1.setModel(tabmode);
        try {
            rs = stmt.executeQuery("SELECT * FROM tickets");
            while (rs.next()) {
                String a = rs.getString("ID_Tiket");
                String b = rs.getString("Nama_Penumpang");
                String c = rs.getString("Penerbangan");
                String d = rs.getString("Kelas");
                String e = rs.getString("Kursi");
                String f = rs.getString("Food");
                String g = rs.getString("Suite");
                String h = rs.getString("Tujuan");
                String i = rs.getString("Waktu_Berangkat");               
                String[] data = {a, b, c, d, e, f, g, h, i};
                tabmode.addRow(data);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading tickets: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelAirport = new javax.swing.JLabel();
        jLabelFlight = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButtonCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButtonHapusTiket = new javax.swing.JButton();
        jButtonByPenerbangan = new javax.swing.JButton();
        jButtonLihatSemua = new javax.swing.JButton();
        jButtonEditKelas = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButtonEkonomi = new javax.swing.JButton();
        jButtonBisnis = new javax.swing.JButton();
        jButtonEksekutif = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightAdministration/images/user.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, -1, -1));

        jLabelAirport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightAdministration/images/airports.png"))); // NOI18N
        jLabelAirport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAirportMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabelFlight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightAdministration/images/timetable.png"))); // NOI18N
        jLabelFlight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFlightMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelFlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightAdministration/images/PlaneSmall.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightAdministration/images/TiketSmall.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 60, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightAdministration/images/menu hamburger.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 60, 700));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 300, 30));

        jButtonCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightAdministration/images/magnifier.png"))); // NOI18N
        jButtonCari.setText("Cari");
        jButtonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCariActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, -1, 30));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Tiket", "Nama Penumpang", "Penerbangan", "Kelas", "Kursi", "Tujuan", "Waktu Berangkat"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 71, 930, 450));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tools", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Sitka Heading", 1, 24))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jButtonHapusTiket.setLabel("Hapus Tiket");
        jButtonHapusTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusTiketActionPerformed(evt);
            }
        });

        jButtonByPenerbangan.setText("By Penerbangan");
        jButtonByPenerbangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonByPenerbanganActionPerformed(evt);
            }
        });

        jButtonLihatSemua.setText("Lihat semua");
        jButtonLihatSemua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLihatSemuaActionPerformed(evt);
            }
        });

        jButtonEditKelas.setText("Edit Kelas");
        jButtonEditKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditKelasActionPerformed(evt);
            }
        });

        jLabel6.setText("Kelas:");

        jButtonEkonomi.setText("Ekonomi");
        jButtonEkonomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEkonomiActionPerformed(evt);
            }
        });

        jButtonBisnis.setText("Bisnis");
        jButtonBisnis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBisnisActionPerformed(evt);
            }
        });

        jButtonEksekutif.setText("Eksekutif");
        jButtonEksekutif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEksekutifActionPerformed(evt);
            }
        });

        jButtonAdd.setText("Add Ticket");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonLihatSemua, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonByPenerbangan, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonHapusTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButtonEditKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonEksekutif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonBisnis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonEkonomi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButtonLihatSemua)
                .addGap(18, 18, 18)
                .addComponent(jButtonByPenerbangan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEkonomi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBisnis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEksekutif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jButtonAdd)
                .addGap(18, 18, 18)
                .addComponent(jButtonEditKelas)
                .addGap(18, 18, 18)
                .addComponent(jButtonHapusTiket)
                .addGap(17, 17, 17))
        );

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 70, 150, 440));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 1150, 540));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(0, 153, 255));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightAdministration/images/TIket.png"))); // NOI18N

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(14, 14, 14))
        );

        jPanel6.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 90, 90));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel1.setText("Ticket");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jPanel15.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlightAdministration/images/pesawat.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 1250, 430));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 1150, 130));

        jPanel14.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 1150, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabelAirportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAirportMouseClicked
        // TODO add your handling code here:
          new airport().setVisible(true);
          dispose();
    }//GEN-LAST:event_jLabelAirportMouseClicked

    private void jLabelFlightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFlightMouseClicked
        // TODO add your handling code here:
         new flight().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelFlightMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
         new Pesawat().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        new mainmenu().setVisible(true);
          dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButtonLihatSemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLihatSemuaActionPerformed
        // TODO add your handling code here:
        loadAllTickets();                 
    }//GEN-LAST:event_jButtonLihatSemuaActionPerformed

    private void jButtonByPenerbanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonByPenerbanganActionPerformed
        // TODO add your handling code here:
        String flightNumber = JOptionPane.showInputDialog(this, "Enter Flight Number:");
        if (flightNumber != null && !flightNumber.trim().isEmpty()) {
            currentFlightNumber = flightNumber;
            Object[] Baris = {"ID Tiket", "Nama Penumpang", "Penerbangan", "Kelas", "Kursi", "Food", "Suite", "Tujuan", "Waktu Berangkat"};
            DefaultTableModel tabmode = new DefaultTableModel(null, Baris);
            jTable1.setModel(tabmode);
            try {
                rs = stmt.executeQuery("SELECT * FROM tickets WHERE Penerbangan = '" + flightNumber + "'");
                while (rs.next()) {
                    String a = rs.getString("ID_Tiket");
                    String b = rs.getString("Nama_Penumpang");
                    String c = rs.getString("Penerbangan");
                    String d = rs.getString("Kelas");
                    String e = rs.getString("Kursi");
                    String f = rs.getString("Food");
                    String g = rs.getString("Suite");
                    String h = rs.getString("Tujuan");
                    String i = rs.getString("Waktu_Berangkat");
                    String[] data = {a, b, c, d, e, f, g, h, i};
                    tabmode.addRow(data);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error filtering by flight: " + e.getMessage());
            }
        } 
    }//GEN-LAST:event_jButtonByPenerbanganActionPerformed

    private void jButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCariActionPerformed
        // TODO add your handling code here:
        String searchText = jTextField1.getText().trim();
        Object[] Baris = {"ID Tiket", "Nama Penumpang", "Penerbangan", "Kelas", "Kursi", "Food", "Suite", "Tujuan", "Waktu Berangkat"};
        DefaultTableModel tabmode = new DefaultTableModel(null, Baris);
        jTable1.setModel(tabmode);
        try {
            rs = stmt.executeQuery("SELECT * FROM tickets WHERE Nama_Penumpang LIKE '%" + searchText + "%'");
            while (rs.next()) {
                String a = rs.getString("ID_Tiket");
                String b = rs.getString("Nama_Penumpang");
                String c = rs.getString("Penerbangan");
                String d = rs.getString("Kelas");
                String e = rs.getString("Kursi");
                String f = rs.getString("Food");
                String g = rs.getString("Suite");
                String h = rs.getString("Tujuan");
                String i = rs.getString("Waktu_Berangkat");
                String[] data = {a, b, c, d, e, f, g, h, i};
                tabmode.addRow(data);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error searching tickets: " + e.getMessage());
        } 
    }//GEN-LAST:event_jButtonCariActionPerformed

    private void jButtonEditKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditKelasActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            String ticketId = jTable1.getValueAt(selectedRow, 0).toString();
            String currentClass = jTable1.getValueAt(selectedRow, 3).toString();
            String newClass = JOptionPane.showInputDialog(this, "Enter new class for ticket ID " + ticketId + " (current: " + currentClass + "):");
            if (newClass != null && !newClass.trim().isEmpty()) {
                try {
                    stmt.executeUpdate("UPDATE tickets SET Kelas = '" + newClass + "' WHERE ID_Tiket = '" + ticketId + "'");
                    loadAllTickets();
                    JOptionPane.showMessageDialog(this, "Ticket class updated successfully");
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Error updating ticket class: " + e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a ticket to edit");
        }
    }//GEN-LAST:event_jButtonEditKelasActionPerformed

    private void jButtonHapusTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusTiketActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            String ticketId = jTable1.getValueAt(selectedRow, 0).toString();
            int confirm = JOptionPane.showConfirmDialog(this, "Delete ticket ID: " + ticketId + "?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    stmt.executeUpdate("DELETE FROM tickets WHERE ID_Tiket = '" + ticketId + "'");
                    loadAllTickets();
                    JOptionPane.showMessageDialog(this, "Ticket deleted successfully");
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Error deleting ticket: " + e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a ticket to delete");
        }
    }//GEN-LAST:event_jButtonHapusTiketActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        new ticketUI().setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButtonEkonomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEkonomiActionPerformed
        // TODO add your handling code here:
        if (currentFlightNumber == null) {
            JOptionPane.showMessageDialog(this, "Please filter by Penerbangan first.");
            return;
        }

        Object[] Baris = {"ID Tiket", "Nama Penumpang", "Penerbangan", "Kelas", "Kursi", "Food", "Suite", "Tujuan", "Waktu Berangkat"};
        DefaultTableModel tabmode = new DefaultTableModel(null, Baris);
        jTable1.setModel(tabmode);

        try {
            String query = "SELECT * FROM tickets WHERE Penerbangan = '" + currentFlightNumber + "' AND Kelas = 'Ekonomi'";
            rs = stmt.executeQuery(query);
            while (rs.next()) {
                String a = rs.getString("ID_Tiket");
                String b = rs.getString("Nama_Penumpang");
                String c = rs.getString("Penerbangan");
                String d = rs.getString("Kelas");
                String e = rs.getString("Kursi");
                String f = rs.getString("Food");
                String g = rs.getString("Suite");
                String h = rs.getString("Tujuan");
                String i = rs.getString("Waktu_Berangkat");
                String[] data = {a, b, c, d, e, f, g, h, i};
                tabmode.addRow(data);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error filtering by class: " + e.getMessage());
}
    }//GEN-LAST:event_jButtonEkonomiActionPerformed

    private void jButtonBisnisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBisnisActionPerformed
        // TODO add your handling code here:
        if (currentFlightNumber == null) {
            JOptionPane.showMessageDialog(this, "Please filter by Penerbangan first.");
            return;
        }

        Object[] Baris = {"ID Tiket", "Nama Penumpang", "Penerbangan", "Kelas", "Kursi", "Food", "Suite", "Tujuan", "Waktu Berangkat"};
        DefaultTableModel tabmode = new DefaultTableModel(null, Baris);
        jTable1.setModel(tabmode);

        try {
            String query = "SELECT * FROM tickets WHERE Penerbangan = '" + currentFlightNumber + "' AND Kelas = 'Bisnis'";
            rs = stmt.executeQuery(query);
            while (rs.next()) {
                String a = rs.getString("ID_Tiket");
                String b = rs.getString("Nama_Penumpang");
                String c = rs.getString("Penerbangan");
                String d = rs.getString("Kelas");
                String e = rs.getString("Kursi");
                String f = rs.getString("Food");
                String g = rs.getString("Suite");
                String h = rs.getString("Tujuan");
                String i = rs.getString("Waktu_Berangkat");
                String[] data = {a, b, c, d, e, f, g, h, i};
                tabmode.addRow(data);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error filtering by class: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonBisnisActionPerformed

    private void jButtonEksekutifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEksekutifActionPerformed
        // TODO add your handling code here:
        if (currentFlightNumber == null) {
            JOptionPane.showMessageDialog(this, "Please filter by Penerbangan first.");
            return;
        }

        Object[] Baris = {"ID Tiket", "Nama Penumpang", "Penerbangan", "Kelas", "Kursi", "Food", "Suite", "Tujuan", "Waktu Berangkat"};
        DefaultTableModel tabmode = new DefaultTableModel(null, Baris);
        jTable1.setModel(tabmode);

        try {
            String query = "SELECT * FROM tickets WHERE Penerbangan = '" + currentFlightNumber + "' AND Kelas = 'Eksekutif'";
            rs = stmt.executeQuery(query);
            while (rs.next()) {
                String a = rs.getString("ID_Tiket");
                String b = rs.getString("Nama_Penumpang");
                String c = rs.getString("Penerbangan");
                String d = rs.getString("Kelas");
                String e = rs.getString("Kursi");
                String f = rs.getString("Food");
                String g = rs.getString("Suite");
                String h = rs.getString("Tujuan");
                String i = rs.getString("Waktu_Berangkat");
                String[] data = {a, b, c, d, e, f, g, h, i};
                tabmode.addRow(data);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error filtering by class: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonEksekutifActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        new TiketInput().setVisible(true);
    }//GEN-LAST:event_jButtonAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ticketUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ticketUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ticketUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ticketUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ticketUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBisnis;
    private javax.swing.JButton jButtonByPenerbangan;
    private javax.swing.JButton jButtonCari;
    private javax.swing.JButton jButtonEditKelas;
    private javax.swing.JButton jButtonEkonomi;
    private javax.swing.JButton jButtonEksekutif;
    private javax.swing.JButton jButtonHapusTiket;
    private javax.swing.JButton jButtonLihatSemua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelAirport;
    private javax.swing.JLabel jLabelFlight;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
