/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FlightAdministration;

import java.sql.Connection;
import java.sql.DriverManager;
import java.util.UUID;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static FlightAdministration.airport.conn;
import static FlightAdministration.airport.stmt;
import static FlightAdministration.airportinput.conn;

/**
 *
 * @author acern
 */
public class TiketInput extends javax.swing.JFrame {

    /**
     * Creates new form InputTiket
     */
   
static Connection conn;
static Statement stmt;
static ResultSet rs;

    public TiketInput() {
        koneksi();
        initComponents();
        setLocationRelativeTo(this);
    }
    
    public void koneksi(){
    try{
         Class.forName("com.mysql.cj.jdbc.Driver");
         conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/TubesPBO?useSSL=false&serverTimezone=UTC","root","");
         stmt = conn.createStatement();
     }catch (Exception e){};   
    }
    
    public String generateTicketID(){
        String lastID = "";
        int next = 1;
        try {
            ResultSet rs = stmt.executeQuery("SELECT ID_Tiket FROM tickets ORDER BY ID_Tiket DESC LIMIT 1");
            if(rs.next()){
                lastID = rs.getString("ID_Tiket");
                next = Integer.parseInt(lastID.substring(1)) + 1;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return String.format("T%03d", next);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        PenumpangField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PenerbanganField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        KursiField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TujuanField = new javax.swing.JTextField();
        WaktuBerangkatField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        KelasField = new javax.swing.JComboBox<>();
        jButtonAdd = new javax.swing.JButton();
        jButtonCancelAdd = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        foodField = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PenumpangField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenumpangFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Nama Penumpang");

        jLabel7.setText("INPUT TIKET");

        PenerbanganField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenerbanganFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Penerbangan");

        KursiField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KursiFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Kursi");

        jLabel4.setText("Tujuan");

        TujuanField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TujuanFieldActionPerformed(evt);
            }
        });

        WaktuBerangkatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaktuBerangkatFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Waktu Berangkat");

        jLabel6.setText("Kelas");

        KelasField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ekonomi", "Bisnis", "Eksekutif" }));
        KelasField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KelasFieldActionPerformed(evt);
            }
        });

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonCancelAdd.setText("Cancel");
        jButtonCancelAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelAddActionPerformed(evt);
            }
        });

        jLabel8.setText("Makanan (Jika Bisnis atau Eksekutif)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(foodField)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WaktuBerangkatField)
                    .addComponent(TujuanField)
                    .addComponent(KursiField)
                    .addComponent(PenerbanganField)
                    .addComponent(PenumpangField)
                    .addComponent(KelasField, 0, 173, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAdd)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PenumpangField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(KelasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PenerbanganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KursiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TujuanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WaktuBerangkatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelAdd)
                    .addComponent(jButtonAdd))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PenumpangFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenumpangFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PenumpangFieldActionPerformed

    private void PenerbanganFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenerbanganFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PenerbanganFieldActionPerformed

    private void KursiFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KursiFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KursiFieldActionPerformed

    private void TujuanFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TujuanFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TujuanFieldActionPerformed

    private void WaktuBerangkatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaktuBerangkatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WaktuBerangkatFieldActionPerformed

    private void KelasFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelasFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KelasFieldActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        try {
            Datum<Tiket> tiket = new Datum<>();
            String idTiket = generateTicketID();
            String namaPenumpang = PenumpangField.getText().trim();
            String kelas = KelasField.getSelectedItem().toString().trim();
            String penerbangan = PenerbanganField.getText().trim();
            String kursi = KursiField.getText().trim();
            String tujuan = TujuanField.getText().trim();
            String waktuBerangkat = WaktuBerangkatField.getText().trim();
            String food = foodField.getText().trim();

            if (namaPenumpang.isEmpty() || penerbangan.isEmpty() || kelas.isEmpty() || kursi.isEmpty() || tujuan.isEmpty() || waktuBerangkat.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
                return;
            }

            switch (kelas) {
                case "Ekonomi":
                    tiket.setIsi(new TiketEkonomi(idTiket, namaPenumpang, kelas, penerbangan, kursi, tujuan, waktuBerangkat));
                    break;
                case "Bisnis":
                    tiket.setIsi(new TiketBisnis(true, idTiket, namaPenumpang, kelas, penerbangan, kursi, tujuan, waktuBerangkat));
                    break;
                case "Eksekutif":
                    tiket.setIsi(new TiketEksekutif(true, true, idTiket, namaPenumpang, kelas, penerbangan, kursi, tujuan, waktuBerangkat));
                    break;
                default:
                    break;
            }
            String sql = "INSERT INTO tickets (ID_Tiket, Nama_Penumpang, Penerbangan, Kelas, Kursi, Food, Suite, Tujuan, Waktu_Berangkat) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, idTiket);
            pstmt.setString(2, namaPenumpang);
            pstmt.setString(3, penerbangan);
            pstmt.setString(4, kelas);
            pstmt.setString(5, kursi);
            pstmt.setString(6, null);
            pstmt.setString(7, null);
            pstmt.setString(8, tujuan);
            pstmt.setString(9, waktuBerangkat);
            if ("Bisnis".equals(kelas)) {
                pstmt.setString(6, food);
            }
            else if ("Eksekutif".equals(kelas)) {
                pstmt.setString(6, food);
                pstmt.setBoolean(7, true);
            }
            int rs = pstmt.executeUpdate();
            if (rs > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
                dispose();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonCancelAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelAddActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonCancelAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiketInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiketInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiketInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiketInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TiketInput().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> KelasField;
    private javax.swing.JTextField KursiField;
    private javax.swing.JTextField PenerbanganField;
    private javax.swing.JTextField PenumpangField;
    private javax.swing.JTextField TujuanField;
    private javax.swing.JTextField WaktuBerangkatField;
    private javax.swing.JTextField foodField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancelAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
